### ISSUE TITLE
ASCL decoder input/output

### ISSUE THREAD

**Issue by dtoppani-twist** [aff3ct/my_project_with_aff3ct#4]
I trying to use aff3ct as a library, and more specifically only the encoders and decoders. It is not for a typical telecommunication application.

I have the following test code:

`std::vector<std::string> args = {"aff3ct", "-N", "32768", "-K", "16384", "-D", "ASCL", "--enc-fb-noise", "1.0" };
    const char * argv[9];
    for(int k=0;k<args.size();k++)
        argv[k] = args[k].c_str();
    tools::Argument_handler ah(args.size(), argv);

    params_cdc = new factory::Codec_polar::parameters("cdc");
    factory::CRC::parameters params_crc;

    tools::Argument_map_info arg_info;
    tools::Argument_map_group arg_group;

    params_cdc->get_description(arg_info);
    std::vector<std::string> warnings, errors;
    auto arg_vals = ah.parse_arguments(arg_info, warnings, errors);

    params_cdc->store(arg_vals);
    crc = new module::CRC_polynomial_fast(_kc, "0x04C11DB7", 32);
    auto r = params_cdc->build(crc);
    std::vector<int> Ks(_kc), Ns(_n);
    for(int k=0;k<_k;k++) //create a test input that looks like 100100100...
        Ks[k] = k % 3 == 0? 1: 0;
    std::vector<int> Ks2(_k);
    crc->build(Ks, Ks2); //run crc
    r->get_encoder()->encode(Ks2, Ns); //encode
    std::vector<float> Ys(_n);
    auto one_r = log(0.9999/0.0001);
    auto zero_r = log(0.0001/0.9999);
    for(int n=0;n<_n;n++) //convert to decoder input - I assume the input is log-likelihood ratios?
        Ys[n] = Ns[n] > 0 ? one_r : zero_r;
    std::vector<int> Vs(_k);
    r->get_decoder_siho()->decode_siho(Ys, Vs);`//decode

I don't get any exceptions and the encoding output seems normal. However for the decoder, I believe from other examples the expected soft input are LLRs. The output of the decoder is quite strange:
0
-2147483648 (0x80000000)
-2147483648
0
-2147483648
-2147483648
...

The pattern is similar to the original input but 1 becomes 0 and 0 becomes 0x80000000... I tried other input ranges to the decoder with same output or no reasonable output..

**Comment by bonben** [comment]
Hi Dominique.

I didn't dig very deep into the code, but I think it's just a simple problem of representation.
In some of our decoders, the binary "1s" output data can be represented as (-2147483648) 0x8000000 for low level optimization concerns.
Therefore, treat these as ones and all well be fine.
You can for example use a Monitor_BFER module in order to verify that Vs and Ks are equal.
Furthermore, the step where you convert binary inputs to LLRs can be done with a Modulator/Demodulator couple.

I hope this will help you, don't hesitate to come back to us if needed!
